<script type="text/javascript">
	<!--//--><![CDATA[//><!--
		pre_url = "<?php echo(the_permalink()); ?>";	
		sub_url = "<?php echo(get_option('siteurl')); ?>/wp-comments-post.php";
				
		comment_text = "<?php echo(str_replace('"', '\"', str_replace('&gt;', '>', str_replace('&lt;', '<', stripslashes($_POST['comment']))))); ?>";
	//--><!]]>
</script>

<?php
/*
please see wp-commentpreview.php for more information
*/

$wp_comment_preview = 1;

$content = file_get_contents(TEMPLATEPATH . '/comments.php');

// convert the file content to a php code
$content = preg_replace('/[\/][\/].*[?]/', '?', $content);
$content = preg_replace('/[\/][\/].*/', '', $content);
$content = preg_replace('/[\/][\*].*[\*][\/]/', '', $content);

// rename the author field, to prevent searching for author on selft-submit
$content = str_replace('name="author"', 'name="cauthor"', $content);

$content = str_replace('<?php', '\');', $content);
$content = str_replace('?' . '>', '; echo(\'', $content);
$content = 'echo(\'' . $content . '\');';


// display only the preview

if(isset($_POST['preview'])) {
	
	// prepare comments array if preview
	$comment->comment_ID = '1';
	$comment->comment_post_ID = $_POST['comment_post_ID'];
	$auth = $_POST['cauthor'];
	if(strcmp($auth, '') == 0)
		$auth = '<a href="' . get_option('siteurl') . '/wp-admin/profile.php">' . $user_identity . '</a>';
	$comment->comment_author = $auth;
	$comment->comment_author_email = '';
	$comment->comment_author_url = stripslashes($_POST['url']);
	$comment->comment_author_IP = '';
	$comment->comment_date = current_time('mysql');
	$comment->comment_date_gmt = current_time('mysql', 1);
	$comment->comment_content = str_replace('&gt;', '>', str_replace('&lt;', '<', stripslashes($_POST['comment'])));
	$comment->comment_karma = 0;
	$comment->comment_approved = 1;
	$comment->comment_agent = '';
	$comment->comment_type = '';
	$comment->comment_parent = 0;
	$comment->user_id = 0;
	
	$comments = array($comment);
	
	// replace title
	if(preg_match('#<h[0-9]*.*the_title.*/h[0-9]*>#', $content, $matches)) {
		preg_match('#<h[0-9]*[^>]*>#', $matches[0], $beginning);
		preg_match('#</h[0-9]*[^>]*>#', $matches[0], $ending);
		
		$content = str_replace($matches[0], $beginning[0] . '<span id="commentpreview">Comment Preview</span>' . $ending[0], $content);
	}
	
	// replace values of fields
	
	if(preg_match('#<input.*name="cauthor"[^>]*>#', $content, $matches)) {
		$replace_string = preg_replace('/value="[^"]*"/', 'value="' . $_POST['cauthor'] . '"', $matches[0]);
		$content = str_replace($matches[0], $replace_string, $content);
	}
	if(preg_match('#<input.*name="email"[^>]*>#', $content, $matches)) {
		$replace_string = preg_replace('/value="[^"]*"/', 'value="' . $_POST['email'] . '"', $matches[0]);
		$content = str_replace($matches[0], $replace_string, $content);
	}
	if(preg_match('#<input.*name="url"[^>]*>#', $content, $matches)) {
		$replace_string = preg_replace('/value="[^"]*"/', 'value="' . $_POST['url'] . '"', $matches[0]);
		$content = str_replace($matches[0], $replace_string, $content);
	}
}

// add quicktags
$content = preg_replace('/<textarea/','<div id="quicktags"></div><textarea', $content);

// add required fields and buttons
$content = preg_replace('/<input[^>]*type="submit"[^>]*>/', '
	<noscript>If you have enabled JavaScript, you will be able to preview your comment before submitting.<br /></noscript>
	<input type="hidden" name="author" id="actualauthor" value="" />
	<span id="previewbutton"><input name="preview" type="submit" id="preview" tabindex="5" value="' . __('Preview Comment', 'wp-commentpreview') . '" onclick="return dosubmit(1, pre_url);" /></span>
	<span id="submitbutton"><input name="submit" type="submit" id="submit" tabindex="6" value="Submit Comment" onclick="return dosubmit(0, sub_url);" /></span>
			
', $content);

$content .= 'echo("\n\n<!-- comment quicktags and preview code generated by \'WP-CommentPreview\' - http://adahas.com/work/wp-commentpreview/ -->\n\n");';

$content = str_replace("\n", "", $content);
$content = str_replace("\r", "", $content);
$content = str_replace(";", ";\n", $content);

eval ($content);

?>
<script type="text/javascript">
	<!--//--><![CDATA[//><!--
	if(pre_url != '') {
		
		var edCanvas = document.getElementById("comment");
		document.getElementById('previewbutton').className = "visible";
		document.getElementById("comment").value = comment_text;
		edToolbar();
	}
	//--><!]]>
</script>